# Aider configuration for AI-Tools project
# Docs: https://aider.chat/docs/config/aider_conf.html

# Default model — cheap for everyday edits
# Override with: aider --model openai/claude-sonnet (for complex work)
model: openai/claude-haiku
openai-api-base: http://localhost:4000
openai-api-key: not-needed

# Git settings
auto-commits: true
dirty-commits: true
attribute-author: true
attribute-committer: false

# Editor settings
edit-format: diff
stream: true
pretty: true

# Context
map-tokens: 1024
map-refresh: auto
